name: Checkout
on: [push]

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        permissions:
            contents: read # or write if you plan to make commits or push
            actions: write # Allows the workflow to write to the logs and status
        steps:
            - name: List Files Before
              run: ls -a
            - name: Checkout Repository
              uses: actions/checkout@v4 # Recommended to use the official checkout action
            - name: List Files After Checkout
              run: ls -a