name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting an error message with parameters
              run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col = 5,endColumn=7::Missing semicolon"
            - name: Setting an debug message with parameters
              run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col = 5,endColumn=7::Missing semicolon"
            - name: Setting an warning message with parameters
              run: echo "::error title=Warning title,file=app.js,line=2,endLine=3,col = 5,endColumn=7::Missing semicolon"
            - name: Setting an notice message with parameters
              run: echo "::error title=Notice title,file=app.js,line=2,endLine=3,col = 5,endColumn=7::Missing semicolon"
            - name: Group of logs
              run: |
                echo "::group::My group title"
                echo "Inside group"
                echo "::endgroup::"
            - name: Masking value
              run: echo "::add-mask::Secret String"
            - name: Echo a secret
              run: echo "Secret String"